spring:

  datasource:
    url: jdbc:postgresql://10.245.140.9:5432/iiot_platform
    username: vivek
    password: vivek@123

  jpa:
    hibernate:
      ddl-auto: validate

  cassandra:
    contact-points: cassandra-prod
    port: 9042
    local-datacenter: datacenter1
    keyspace-name: iiot_keyspace