##spring:
##
##  datasource:
##    url: jdbc:postgresql://localhost:5432/iiot_platform
##    username: postgres
##    password: postgres@123
##    driver-class-name: org.postgresql.Driver
##
##  jpa:
##    hibernate:
##      ddl-auto: none
##    show-sql: true
##    properties:
##      hibernate:
##        format_sql: true
##        dialect: org.hibernate.dialect.PostgreSQLDialect
#
#
#spring:
#
#  datasource:
#    url: jdbc:postgresql://localhost:5432/iiot_platform
#    username: postgres
#    password: postgres@123
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#
#  # 🔥 THIS is the IMPORTANT FIX
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.cassandra.CassandraAutoConfiguration
#      - org.springframework.boot.autoconfigure.data.cassandra.CassandraDataAutoConfiguration
#      - org.springframework.boot.autoconfigure.cassandra.CassandraReactiveAutoConfiguration
#      - org.springframework.boot.autoconfigure.cassandra.CassandraReactiveHealthContributorAutoConfiguration
#      - org.springframework.boot.actuate.autoconfigure.cassandra.CassandraHealthContributorAutoConfiguration
#spring:
# mail:
#  host: smtp.gmail.com
#  port: 587
#  username: guptaaeadhana05@gmail.com
#  password: "CollegesspassA12@1234783jdjehd"
# properties:
#  mail:
#  smtp:
#  auth: true
#  starttls:
#  enable: true
#  datasource:
#    url: jdbc:postgresql://localhost:5432/iiot_platform
#    username: postgres
#    password: postgres@123
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#
#  cassandra:
#    contact-points: localhost
#    port: 9042
#    keyspace-name: iiot_platform
#    local-datacenter: datacenter1
#    schema-action: none
#
#  web:
#    error:
#      include-message: always
#      include-stacktrace: always
#
#logging:
#  level:
#    org.springframework: INFO
#    com.enterprise.iiot: DEBUG

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: guptaaradhana05@gmail.com
    password: qgpd ukjt ufza jtuj

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
<<<<<<< HEAD
    url: jdbc:postgresql://localhost:5432/iiot_platform
    username: postgres
    password: postgres@123
=======
    url:  jdbc:postgresql://100.121.90.6:5432/iiot_platform
    username: vivek
    password: vivek@123
>>>>>>> 9e08fb9 (Initial commit)
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cassandra:
    contact-points: localhost
    port: 9042
    keyspace-name: iiot_platform
    local-datacenter: datacenter1
    schema-action: none

web:
  error:
    include-message: always
    include-stacktrace: always

logging:
  level:
    org.springframework: INFO
    com.enterprise.iiot: DEBUG