spring:

  datasource:
<<<<<<< HEAD
    url: jdbc:postgresql://localhost:5432/iiot_platform
    username: postgres
    password: postgres@123
=======
    url: jdbc:postgresql://100.121.90.6:5432/iiot_platform
    username: vivek
    password: vivek@123
>>>>>>> 9e08fb9 (Initial commit)

  jpa:
    hibernate:
      ddl-auto: validate

  cassandra:
    contact-points: cassandra-prod
    port: 9042
    local-datacenter: datacenter1
    keyspace-name: iiot_keyspace