import "../styles/Report.css";

import {
    FileText,
    Building2,
    Cpu,
    Thermometer,
    IndianRupee,
    TriangleAlert,
    Calendar,
    User
} from "lucide-react";

export default function ViewReport() {

    return (

        <div className="report-page">

            <div className="page-header">

                <div>

                    <h2>Steam Saving Report</h2>

                    <p>
                        Report Preview
                    </p>

                </div>

                <div className="header-actions">

                    <button className="refresh-btn">

                        Print

                    </button>

                    <button className="primary-btn">

                        Download PDF

                    </button>

                </div>

            </div>

            {/* Summary */}

            <div className="report-summary">

                <div className="summary-item">

                    <Building2 size={22}/>

                    <div>

                        <span>Customer</span>

                        <h4>BridgeStone</h4>

                    </div>

                </div>

                <div className="summary-item">

                    <Cpu size={22}/>

                    <div>

                        <span>Devices</span>

                        <h4>126</h4>

                    </div>

                </div>

                <div className="summary-item">

                    <Thermometer size={22}/>

                    <div>

                        <span>Sensors</span>

                        <h4>486</h4>

                    </div>

                </div>

                <div className="summary-item">

                    <IndianRupee size={22}/>

                    <div>

                        <span>Total Saving</span>

                        <h4>₹12.45 L</h4>

                    </div>

                </div>

            </div>

            {/* Report Details */}

            <div className="report-preview">

                <div className="preview-header">

                    <FileText size={30}/>

                    <div>

                        <h3>Industrial IIoT Steam Report</h3>

                        <p>

                            Steam Saving Analysis

                        </p>

                    </div>

                </div>

                <div className="preview-grid">

                    <div>

                        <label>Report Type</label>

                        <p>Monthly</p>

                    </div>

                    <div>

                        <label>Generated By</label>

                        <p>Admin</p>

                    </div>

                    <div>

                        <label>Generated Date</label>

                        <p>13 Jul 2026</p>

                    </div>

                    <div>

                        <label>Date Range</label>

                        <p>01 Jul - 13 Jul</p>

                    </div>

                </div>

            </div>

            {/* KPI */}

            <div className="report-kpi">

                <div className="kpi-card">

                    <TriangleAlert/>

                    <h2>12</h2>

                    <span>Total Alerts</span>

                </div>

                <div className="kpi-card">

                    <Cpu/>

                    <h2>119</h2>

                    <span>Online Devices</span>

                </div>

                <div className="kpi-card">

                    <Thermometer/>

                    <h2>472</h2>

                    <span>Active Sensors</span>

                </div>

                <div className="kpi-card">

                    <IndianRupee/>

                    <h2>₹1.84L</h2>

                    <span>Monthly Saving</span>

                </div>

            </div>

            {/* Executive Summary */}

            <div className="executive-summary">

                <h3>

                    Executive Summary

                </h3>

                <p>

                    During this reporting period, 126 Steam Trap devices
                    continuously monitored plant operations.
                    The monitoring system detected 12 alerts,
                    achieved ₹12.45 Lakhs estimated savings,
                    prevented significant steam leakage,
                    and improved plant efficiency.

                </p>

            </div>

        </div>

    );

}